FROM mcr.microsoft.com/dotnet/sdk:5.0 as builder

WORKDIR /src
COPY ./src ./
RUN mkdir /build
WORKDIR /src/DataLoader
RUN dotnet publish -o /build


FROM mcr.microsoft.com/dotnet/aspnet:5.0

RUN adduser --disabled-password --home /app --gecos '' app
WORKDIR /app
RUN chown -R app /app
COPY --from=builder /build .
RUN mkdir /tmp/data
COPY ./data /tmp/data

RUN ls -l /app

ARG run_environment=Production
ENV ASPNETCORE_ENVIRONMENT ${run_environment}
ENV DOTNET_RUNNING_IN_CONTAINER=true \
	ASPNETCORE_URLS=http://+:8080

EXPOSE 8080
ENTRYPOINT ["dotnet", "DataLoader.dll"]
